return {
--   'akinsho/bufferline.nvim',
--   version = "*",
--   -- dependencies = 'nvim-tree/nvim-web-devicons',
--   opts = {
--     options = {
--       offsets = {
--         {
--           filetype = "neo-tree",
--           text = "File Explorer",
--           highlight = "Directory",
--           text_align = "left",
--         }
--       },
--       show_close_icon = false,
--     }
--   },
--   config = function(_, opts)
--     vim.opt.termguicolors = true
--     require("bufferline").setup(opts)
--   end
}
